_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  BACKBONE:
    FREEZE_AT: 3
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
    POOLER_RESOLUTION: 7
  ROI_HEADS:
    NUM_CLASSES: 60
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
DATASETS:
  TRAIN: ('coco_2017_train_nonvoc_split',)
  TEST: ('coco_2017_val_all',)
SOLVER:
  STEPS: (85000, 100000)
  MAX_ITER: 110000
  WEIGHT_DECAY: 5e-5
OUTPUT_DIR: "/Path/to/Output/Dir"
