_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  META_ON: True
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ('coco_2017_train_nonvoc_split',)
  TEST: ('coco_2017_val_nonvoc_split',)
SOLVER:
  BASE_LR: 0.02
  IMS_PER_BATCH: 32
  STEPS: (60000, 80000)
  MAX_ITER: 90000
OUTPUT_DIR:
  ./meta_results/COCO60_pretrain_7
#  ./results/test