_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
    LR_FACTOR: 0.5
  ROI_HEADS:
    CLS_DROPOUT: True
    NUM_CLASSES: 80
    SCORE_THRESH_TEST: 0.01
DATASETS:
  TRAIN: ('coco_2017_train_all',)
  TEST: ('coco_2017_val_all',)
  SHOT: 10
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (1800,)
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
SETTING: 'Incremental'
PHASE: 2
METHOD: 'PTF'
OUTPUT_DIR:
  "/Path/to/Output/Dir"
