_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: False
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ('coco_2017_train_nonvoc_split',)
  TEST: ('coco_2017_val_all',)
SOLVER:
  STEPS: (85000, 100000)
  MAX_ITER: 110000
OUTPUT_DIR:
  "/Path/to/Output/Dir"
