_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: './results/COCO60_pretrain_R101_1x/model_final.pth'
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
  ROI_HEADS:
    NUM_CLASSES: 80
    SCORE_THRESH_TEST: 0.01
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
#    PREDICTOR: 'CosineSimOutputLayers'
#    FREEZE: True
#  PROPOSAL_GENERATOR:
#    FREEZE: True
DATASETS:
  TRAIN: ('coco_2017_train_all',)
  TEST: ('coco_2017_val_all',)
  SHOT: 10
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (800,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
SETTING: 'Incremental'
PHASE: 2
METHOD: 'imprinted'
INIT_ITERS: 400
OUTPUT_DIR:
  ./results/fewshot/coco/R101_imprint_10shot_1
#TEST:
#  EVAL_PERIOD: 100
