_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS:
    './meta_results/COCO60_pretrain_6/model_final.pth'
#    './meta_results/fewshot/coco/10shot_13/model_init.pth'
  MASK_ON: False
  META_ON: True
  RESNETS:
    DEPTH: 50
  BACKBONE:
    FREEZE: True
  ROI_HEADS:
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
#    FREEZE: True
#  PROPOSAL_GENERATOR:
#    FREEZE: True
DATASETS:
  TRAIN: ('coco_2017_train_voc_split',)
  TEST: ('coco_2017_val_voc_split',)
  SHOT: 10
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (450,)
  MAX_ITER: 0
  CHECKPOINT_PERIOD: 50
  WARMUP_ITERS: 0
SETTING: 'Transfer'
PHASE: 2
METHOD: 'meta'
INIT_ITERS: 100
OUTPUT_DIR:
#  ./meta_results/fewshot/coco/10shot_13
  ./meta_results/test
#TEST:
#  EVAL_PERIOD: 50