_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "ProposalNetwork"
  WEIGHTS:
#    'test.pth'
#    './meta_results/fewshot/coco/10shot_27/model_final.pth'
#    "./results/fsdet/COCO20_pretrain_R50/model_final.pth"
#    "./results/COCO60_pretrain_1/model_final.pth"
    "./results/fewshot/coco/coco_imprint_10shot_6/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  BACKBONE:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_2017_train_voc_split',)
  TEST: ('coco_2017_val_voc_split',)
#  SHOT: 10
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (6000, 8000)
  MAX_ITER: 9000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0
#PHASE: 2
OUTPUT_DIR:
  ./results/test