_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: False
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: True
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ('coco_2017_train_nonvoc_split',)
  TEST: ('coco_2017_val_nonvoc_split',)
OUTPUT_DIR:
  ./results/test