_BASE_: "../Base-RCNN-FPN.yaml"
#SEED: 100
MODEL:
  WEIGHTS: "./results/COCO60_pretrain_R101/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
#  BACKBONE:
#    FREEZE: True
  ROI_HEADS:
    NUM_CLASSES: 20
    NAME: 'ReweightedROIHeads'
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
#    PREDICTOR: 'CosineSimOutputLayers'
#    FREEZE: True
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: True

DATASETS:
#  TRAIN: ('coco_10shot_FSRW',)
  TRAIN: ('coco_2017_train_voc_split',)
  TEST: ('coco_2017_val_voc_split',)
#  TEST: ('coco_2017_val',)
  SHOT: 10
SOLVER:
  STEPS: (250, 280)
  WARMUP_ITERS: 50
  MAX_ITER: 300
#  STEPS: (600, 800)
#  WARMUP_ITERS: 50
#  MAX_ITER: 900
  CHECKPOINT_PERIOD: 100
SETTING: 'Transfer'
PHASE: 2
METHOD: 'ours'
INIT_ITERS: 50
OUTPUT_DIR:
#  ./results/fewshot/COCO/voc_ours_10shot_R101
#TEST:
#  EVAL_PERIOD: 100