_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_HEADS:
    NUM_CLASSES: 776
    SCORE_THRESH_TEST: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v0.5_train_base",)
  TEST: ("lvis_v0.5_val_all",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
#DATALOADER:
#  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
#  REPEAT_THRESHOLD: 0.001
OUTPUT_DIR:
  "results/LVISv0.5/base_R101_2"
