_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 200
DATASETS:
  TRAIN: ('fsod_test_5shot',)
  TEST: ('fsod_test',)
SOLVER:
  BASE_LR: 0.02
  STEPS: (3500,)
  MAX_ITER: 4000
  WARMUP_ITERS: 200
SETTING: 'Transfer'
PHASE: 2
METHOD: 'ft'
OUTPUT_DIR:
  ./results/fewshot/FSOD/ft_5shot